### ISSUE TITLE
15. As a user, I want the welcome screen to look pretty

### ISSUE THREAD

**Issue by stacietaylorcima** [the-collab-lab/tcl-3-smart-shopping-list#37]
AC:

* The welcome screen (the screen a user sees before they’ve created their list) looks something like the following (or equivalent, use your creativity!):

![welcome-screen](https://user-images.githubusercontent.com/4306/68095346-759abe80-fe5d-11e9-8c9f-22879fbad048.png)

**Comment by prophen** [comment]
I will write comments on all of the "look pretty" stories (#38, #39, #40) here

**Comment by prophen** [comment]
Semantic UI is the component library I mentioned on Sunday
https://react.semantic-ui.com/

**Comment by prophen** [comment]
![image](https://user-images.githubusercontent.com/3941856/73724924-3e98ab00-46e1-11ea-95e4-d61d9d3111c3.png)

**Comment by prophen** [comment]
![image](https://user-images.githubusercontent.com/3941856/73724983-5c661000-46e1-11ea-8f67-151bbfbf722a.png)

**Comment by prophen** [comment]
![image](https://user-images.githubusercontent.com/3941856/73725046-799ade80-46e1-11ea-884e-b7c4b2defb28.png)

**Comment by prophen** [comment]
![image](https://user-images.githubusercontent.com/3941856/73725173-b1098b00-46e1-11ea-9c8d-fc82a77ec3eb.png)

**Comment by mikeramz86** [comment]
@MonicaDJohnson @prophen @mikeramz86 

<3: My favorite
Thumbs Up: Ok
Thumbs down: No go

**Comment by prophen** [comment]
![image](https://user-images.githubusercontent.com/3941856/73973998-7b7ac280-48d8-11ea-84dc-2479b396e543.png)
Converted the list page to the Semantic components

**Comment by prophen** [comment]
![image](https://user-images.githubusercontent.com/3941856/74068707-2d85bd80-49b1-11ea-9cc5-c925bfaf357b.png)

![image](https://user-images.githubusercontent.com/3941856/74068753-4bebb900-49b1-11ea-9c12-3af8efc18368.png)

I guess this still needs work on the mobile view

![image](https://user-images.githubusercontent.com/3941856/74068823-6f166880-49b1-11ea-9b17-12b1bbc4087c.png)
![image](https://user-images.githubusercontent.com/3941856/74068879-910feb00-49b1-11ea-8196-3c6e02928190.png)

The details dropdown needs the real data

**Comment by prophen** [comment]
https://deploy-preview-67--tcl-3-smart-shopping-list.netlify.com/
